namespace :import do
  desc "Import data from CSV file"
  task custom_data: :environment do
    require 'csv'
    
    file_path = Rails.root.join('public', 'csv', 'test-file.csv')

    # CSV.foreach(file_path, headers: true) do |row|
    #   # Access row data here
    #   row_data = row.to_hash
    #   # Process row data here
    #   debugger
    #   puts "Row data: #{row_data}"
    # end

    CSV.foreach(file_path, headers: true) do |row|
      # Access row data here
      row_data = row.to_hash
      # Process row data here
      info = Information.new(
        turnover: row_data['Umsatz (ohne Soll/Haben-Kz)'],
        debit_credit_indicator: row_data['Soll/Haben-Kennzeichen'],
        currency: row_data['WKZ Umsatz'],
        exchange_rate: row_data['Kurs'],
        base_turnover: row_data['Basis-Umsatz'],
        currency_base_turnover: row_data['WKZ Basis-Umsatz'],
        account: row_data['Konto'],
        contra_account: row_data['Gegenkonto (ohne BU-Schl�ssel)'],
        posting_key: row_data['BU-Schl�ssel'],
        receipt_date: Date.parse(row_data['Belegdatum']),
        document_field_1: row_data['Belegfeld 1'],
        document_field_2: row_data['Belegfeld 2'],
        discount: row_data['Skonto'],
        booking_text: row_data['Buchungstext'],
        post_lock: row_data['Postensperre'],
        various_address_numbers: row_data['Diverse Adressnummer'],
        business_partner_bank: row_data['Gesch�ftspartnerbank'],
        facts: row_data['Sachverhalt'],
        interest_lock: row_data['Zinssperre'],
        document_link: row_data['Beleglink'],
        receipt_info_type_1: row_data['Beleginfo - Art 1'],
        receipt_info_content_1: row_data['Beleginfo - Inhalt 1'],
        receipt_info_type_2: row_data['Beleginfo - Art 2'],
        receipt_info_content_2: row_data['Beleginfo - Inhalt 2'],
        receipt_info_type_3: row_data['Beleginfo - Art 3'],
        receipt_info_content_3: row_data['Beleginfo - Inhalt 3'],
        receipt_info_type_4: row_data['Beleginfo - Art 4'],
        receipt_info_content_4: row_data['Beleginfo - Inhalt 4'],
        receipt_info_type_5: row_data['Beleginfo - Art 5'],
        receipt_info_content_5: row_data['Beleginfo - Inhalt 5'],
        receipt_info_type_6: row_data['receipt_info_type_6'],
        receipt_info_content_6: row_data['Beleginfo - Art 6'],
        receipt_info_type_7: row_data['Beleginfo - Art 7'],
        receipt_info_content_7: row_data['Beleginfo - Inhalt 7'],
        receipt_info_type_8: row_data['Beleginfo - Art 8'],
        receipt_info_content_8: row_data['Beleginfo - Inhalt 8'],
        cost_center_1: row_data['KOST1 - Kostenstelle'],
        cost_center_2: row_data['KOST2 - Kostenstelle'],
        food_amount: row_data['Kost-Menge'],
        eu_tax_id: row_data['EU-Land u. UStID (Bestimmung)'],
        eu_tax_rate: row_data['EU-Steuersatz (Bestimmung)'],
        different_tax_type: row_data['Abw. Versteuerungsart'],
        set_of_facts_l_l: row_data['Sachverhalt L+L'],
        functional_addition_l_l: row_data['Funktionserg�nzung L+L'],
        main_function_type: row_data['BU 49 Hauptfunktionstyp'],
        main_function_number: row_data['BU 49 Hauptfunktionsnummer'],
        function_supplement: row_data['BU 49 Funktionserg�nzung'],
        additional_information_art_1: row_data['Zusatzinformation - Art 1'],
        additional_information_content_1: row_data['Zusatzinformation- Inhalt 1'],
        additional_information_art_2: row_data['Zusatzinformation - Art 2'],
        additional_information_content_2: row_data['Zusatzinformation- Inhalt 2'],
        additional_information_art_3: row_data['Zusatzinformation - Art 3'],
        additional_information_content_3: row_data['Zusatzinformation- Inhalt 3'],
        additional_information_art_4: row_data['Zusatzinformation - Art 4'],
        additional_information_content_4: row_data['Zusatzinformation- Inhalt 4'],
        additional_information_art_5: row_data['Zusatzinformation - Art 5'],
        additional_information_content_5: row_data['Zusatzinformation- Inhalt 5'],
        additional_information_art_6: row_data['Zusatzinformation - Art 6'],
        additional_information_content_6: row_data['Zusatzinformation- Inhalt 6'],
        additional_information_art_7: row_data['Zusatzinformation - Art 7'],
        additional_information_content_7: row_data['Zusatzinformation- Inhalt 7'],
        additional_information_art_8: row_data['Zusatzinformation - Art 8'],
        additional_information_content_8: row_data['Zusatzinformation- Inhalt 8'],
        additional_information_art_9: row_data['Zusatzinformation - Art 9'],
        additional_information_content_9: row_data['Zusatzinformation- Inhalt 9'],
        additional_information_art_10: row_data['Zusatzinformation - Art 10'],
        additional_information_content_10: row_data['Zusatzinformation- Inhalt 10'],
        additional_information_art_11: row_data['Zusatzinformation - Art 11'],
        additional_information_content_11: row_data['Zusatzinformation- Inhalt 11'],
        additional_information_art_12: row_data['Zusatzinformation - Art 12'],
        additional_information_content_12: row_data['Zusatzinformation- Inhalt 12'],
        additional_information_art_13: row_data['Zusatzinformation - Art 13'],
        additional_information_content_13: row_data['Zusatzinformation- Inhalt 13'],
        additional_information_art_14: row_data['Zusatzinformation - Art 14'],
        additional_information_content_14: row_data['Zusatzinformation- Inhalt 14'],
        additional_information_art_15: row_data['Zusatzinformation - Art 15'],
        additional_information_content_15: row_data['Zusatzinformation- Inhalt 15'],
        additional_information_art_16: row_data['Zusatzinformation - Art 16'],
        additional_information_content_16: row_data['Zusatzinformation- Inhalt 16'],
        additional_information_art_17: row_data['Zusatzinformation - Art 17'],
        additional_information_content_17: row_data['Zusatzinformation- Inhalt 17'],
        additional_information_art_18: row_data['Zusatzinformation - Art 18'],
        additional_information_content_18: row_data['Zusatzinformation- Inhalt 18'],
        additional_information_art_19: row_data['Zusatzinformation - Art 19'],
        additional_information_content_19: row_data['Zusatzinformation- Inhalt 19'],
        additional_information_art_20: row_data['Zusatzinformation - Art 20'],
        additional_information_content_20: row_data['Zusatzinformation- Inhalt 20'],
        piece: row_data['St�ck'],
        Weight: row_data['Gewicht'],
        payment_method: row_data['Zahlweise'],
        claim_type: row_data['Forderungsart'],
        assessment_year: row_data['Veranlagungsjahr'],
        associated_maturity: row_data['Zugeordnete F�lligkeit'],
        discount_type: row_data['Skontotyp'],
        order_number: row_data['Auftragsnummer'],
        deposit_booking_type: row_data['Buchungstyp (Anzahlungen)'],
        deposit_vat_key: row_data['USt-Schl�ssel (Anzahlungen)'],
        deposit_eu_country: row_data['EU-Land (Anzahlungen)'],
        down_payments_facts_l_l: row_data['Sachverhalt L+L (Anzahlungen)'],
        eu_tax_rate_down_payment: row_data['EU-Steuersatz (Anzahlungen)'],
        down_payment_proceeds_account: row_data['Erl�skonto (Anzahlungen)'],
        origin: row_data['Herkunft-Kz'],
        booking_guid: row_data['Buchungs GUID'],
        kost_date: row_data['KOST-Datum'],
        sepa_mandate_reference: row_data['SEPA-Mandatsreferenz'],
        cash_discount_lock: row_data['Skontosperre'],
        shareholder_name: row_data['Gesellschaftername'],
        party_number: row_data['Beteiligtennummer'],
        identification_number: row_data['Identifikationsnummer'],
        drafter_number: row_data['Zeichnernummer'],
        post_freeze_until: row_data['ostensperre bis'],
        designation_sobil_facts: row_data['Bezeichnung SoBil-Sachverhalt'],
        indicator_sobil_posting: row_data['Kennzeichen SoBil-Buchung'],
        fixation: row_data['Festschreibung'],
        performance_date: row_data['Leistungsdatum'],
        date_assignment_tax_period: row_data['Datum Zuord. Steuerperiode'],
        maturity: row_data['F�lligkeit'],
        general_reversal: row_data['Generalumkehr (GU)'],
        tax_rate: row_data['Steuersatz'],
        country: row_data['Land'],
        billing_reference: row_data['Abrechnungsreferenz'],
        bvv_position: row_data['BVV-Position'],
        eu_country_vat_id_origin: row_data['EU-Land u. UStID (Ursprung)'],
        eu_tax_rate_origin: row_data['EU-Steuersatz (Ursprung)'])_

    puts "Import finished!"
  end
end
